# Generated by Django 3.2.13 on 2022-07-05 23:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='菜单名', max_length=30, unique=True, verbose_name='菜单名')),
                ('icon', models.CharField(blank=True, help_text='图标', max_length=64, verbose_name='图标')),
                ('code', models.CharField(blank=True, help_text='编码', max_length=64, verbose_name='编码')),
                ('url', models.CharField(blank=True, help_text='编码', max_length=256, null=True, unique=True, verbose_name='编码')),
                ('parent', models.ForeignKey(blank=True, help_text='父菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'system_menu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='角色名', max_length=32, unique=True, verbose_name='角色名')),
                ('desc', models.CharField(blank=True, help_text='描述', max_length=50, verbose_name='描述')),
                ('menus', models.ManyToManyField(blank=True, help_text='菜单权限', to='system.Menu', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'system_role',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='名称', max_length=64, verbose_name='名称')),
                ('type', models.CharField(choices=[('unit', '单位'), ('department', '部门')], default='department', help_text='类型', max_length=20, verbose_name='类型')),
                ('parent', models.ForeignKey(blank=True, help_text='父组织架构', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.organization', verbose_name='父组织架构')),
            ],
            options={
                'verbose_name': '组织架构',
                'verbose_name_plural': '组织架构',
                'db_table': 'system_organization',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, help_text='姓名', max_length=20, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='male', help_text='性别', max_length=10, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, help_text='手机号码', max_length=11, verbose_name='手机号码')),
                ('avatar', models.ImageField(blank=True, default='images/default.jpeg', help_text='头像', upload_to='images/%Y/%m', verbose_name='头像')),
                ('position', models.CharField(blank=True, help_text='职位', max_length=64, verbose_name='职位')),
                ('department', models.ForeignKey(blank=True, help_text='部门', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.organization', verbose_name='部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, help_text='角色', to='system.Role', verbose_name='角色')),
                ('superior', models.ForeignKey(blank=True, help_text='主管', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='主管')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'system_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
