# Generated by Django 3.2.13 on 2022-08-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
    ]
