# Generated by Django 3.2.15 on 2022-09-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_permission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='component_path',
            field=models.CharField(blank=True, default='', help_text='组件路径', max_length=256, verbose_name='组件路径'),
        ),
    ]
