# Generated by Django 3.2.15 on 2022-09-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_permission_component_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_visible',
            field=models.BooleanField(blank=True, help_text='是否显示(true为显示,false为隐藏)', null=True, verbose_name='是否显示(true为显示,false为隐藏)'),
        ),
    ]
